config/routes.rb
Rails.application.routes.draw do
  devise_for :member

  resources :home, only: [:index]
  resources :members
  resources :posts
  resources :comments
  resources :vehicles, except: [:show]
  resources :polls
  resources :votes, only: [:create]
  resources :facilities, path: :contacts
  resources :categories, except: [:show]
  resources :transactions do
    member do
      get 'download_receipt'
      put 'verify_payment'
    end
  end
  resources :bookings
  resources :feedbacks
  resources :settings, except: [:show]
  resources :accounts
  resources :inventories

  match '/members/:id/change_password', to: 'members#change_password', via: :get, as: :change_password
  match '/members/:id/update_password', to: 'members#update_password', via: :put, as: :update_password
  match '/members/:id/toggle_admin', to: 'members#toggle_admin', via: :put, as: :toggle_admin
  match '/members/:id/reset_password', to: 'members#reset_password', via: :put, as: :reset_password

  match '/posts/:id/publish', to: 'posts#publish', via: :put, as: :publish_post
  match '/all_transactions', to: 'transactions#all', via: :get, as: :all_transactions
  match '/all_bookings', to: 'bookings#all', via: :get, as: :all_bookings
  match '/booking_calendar', to: 'bookings#calendar', via: :get, as: :booking_calendar
  match '/file_upload', to: 'home#file_upload', via: :post, as: :file_upload
  match '/file_remove', to: 'home#file_remove', via: :delete, as: :file_remove
  get '/financial_reports', to: 'home#financial_reports'
  get '/location', to: 'home#location'
  get '/compose_mail', to: 'home#compose_mail'
  post '/notify_mail', to: 'home#notify_mail'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'fileutils'
  before_action :authenticate_member!, except: [:location]
  before_action :check_admin, only: [:file_upload, :file_remove]

  def index
    @documents = DOCUMENTS_LINKS # Dir.entries("public/documents")
    @duration = Transaction.sub_categories.keys[-1]
    @duration_cf = Transaction.sub_categories.values[-1]
    @due_date = Transaction.new(category: 'Maintenance', sub_category: @duration).due_date
    @due_date_cf = Transaction.new(category: 'CorpusFund', sub_category: @duration_cf).due_date
    @transaction = current_member.transactions.Maintenance.where(sub_category: @duration).first
    @transaction_cf = current_member.transactions.CorpusFund.where(sub_category: @duration_cf).first
  end

  def financial_reports
    @documents = FINANCIAL_REPORTS
  end

  def file_upload
    if params[:my_file].present?
      tmp = params[:my_file].tempfile
      file = File.join("public", "documents", params[:my_file].original_filename)
      FileUtils.cp tmp.path, file
      flash[:notice] = "Document uploaded successfully."
    else
      flash[:error] = "Please select a valid file to upload."
    end
    redirect_to root_path
  end

  def file_remove
    file = File.join("public", "documents", params[:my_file])
    FileUtils.rm file
    flash[:notice] = "Document removed successfully."
    redirect_to root_path
  end

  def location
  end

  def compose_mail
  end

  def notify_mail
    error = []
    err_index = 1
    if params[:recipients].blank?
      error << "#{err_index}. Kindly add one or more recipients"
      err_index += 1
    end
    if params[:subject].blank?
      error << "#{err_index}. Subject can't be blank"
      err_index += 1
    end
    if params[:content].blank?
      error << "#{err_index}. Content can't be blank"
    end
    unless error.empty?
      flash.now[:error] = error.join(";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;").html_safe
      render :compose_mail
    else
      @members = Member.where(id: params[:recipients])
      @members.each do |member|
        MemberMailer.with(member: member, subject: params[:subject], content: params[:content]).notify_members.deliver_later
      end
      flash[:notice] = "Mail sent successfully."
      redirect_to compose_mail_path
    end
  end

  private

  def check_admin
    unless current_member.admin?
      flash[:error] = "You do not have access for this operation"
      redirect_to root_path
    end
  end

end

app/views/home/_feedback.html.erb
<%= form_with(model: @new_feedback, local: true, class: "form-horizontal") do |f| %>
  <div class="modal-header text-center">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="modal-title w-100 font-weight-bold">
      Write to us
    </h3>
  </div>
  <div class="modal-body mx-3">

  <%= f.hidden_field :member_id, value: current_member.id %>

  <div class="form-group">
    <%= f.label :subject, "Subject *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :subject, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: "form-control", rows: 10 %>
    </div>
  </div>

  </div>
  <div class="modal-footer d-flex justify-content-center">
    <div class="col-sm-12" style="text-align: center;">
      <%= button_tag type: 'submit', class: "btn btn-primary", disabled: true do %>
        Send<i class="fa fa-paper-plane-o fa-fw"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/_mail_form.html.erb
<%= form_tag('/notify_mail', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :recipients, "Recipients *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 autocomplete">
      <%= select_tag(:recipients, options_for_select(flats_list_with_id, params[:recipients]), placeholder: 'Select Recipients', class: "form-control", style: "display: none;", multiple: true) %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :subject, "Subject *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= text_field_tag :subject, params[:subject], class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :content, "Content *",  class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%#= text_area_tag :content, params[:content], class: "form-control", rows: 8, required: true, as: :trix_editor %>
      <input id="content" name="content" value="<%= params[:content] %>" type="hidden" name="content" class="form-control" rows="8" />
      <trix-editor input="content" class="trix-content"></trix-editor>
    </div>
  </div>
  <div class="col-sm-12 flex-buttons">
    <%= link_to 'Cancel', root_path, class: "mtop10 btn btn-default" %>
    <%= button_tag type: 'submit', value: 'Send', class: "mleft10 mtop10 btn btn-primary" do %>
      Send<i class="fa fa-paper-plane-o fa-fw"></i>
    <% end %>
  </div>
<% end %>

app/views/home/compose_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>New Message</h3></div>
        <div class="panel-body panel30">
          <%= render 'mail_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/financial_reports.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <div class="flex-box">
            Financial Reports
          </div>
        </h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body panel30 financial-reports-wrapper">
        <ul class="list-group">
          <% @documents.each do |file_name, file_path| %>
            <li class="list-group-item">
              <%= link_to (file_path + file_name), target: '_blank' do %>
                <%= file_name %>
                <i class="fa fa-file-pdf-o fa-fw" title="View"></i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3 class="lpad20">Welcome <%= current_member.name %> <span class="label label-default">(<%= current_member.login %>)</span></h3>
    <div class="row">
      <div class="col-lg-3 mtop10">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Quick Links</h3>
          </div>
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
              <li>
                <%= link_to financial_reports_path do %>
                  <i class="fa fa-money fa-fw"></i>
                  Financial Reports
                <% end %>
              </li>
              <li>
                <%= link_to member_path(current_member) do %>
                  <i class="fa fa-user fa-fw"></i>
                  My Profile
                <% end %>
              </li>
              <li>
                <%= link_to vehicles_path do %>
                  <i class="fa fa-car fa-fw"></i>
                  My Vehicle(s)
                <% end %>
              </li>
              <li>
                <%= link_to transactions_path do %>
                  <i class="fa fa-money fa-fw"></i>
                  My Transaction(s)
                <% end %>
              </li>
              <li>
                <%= link_to bookings_path do %>
                  <i class="fa fa-birthday-cake fa-fw"></i>
                  My Party Hall Booking(s)
                <% end %>
              </li>
              <li>
                <%= link_to change_password_path(current_member) do %>
                  <i class="fa fa-key fa-fw"></i>
                  Change Password
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 mtop10">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Notice Board</h3>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              <li class="list-group-item">
                <% if @transaction.present? %>
                  Thanks for your maintenance payment for <b><%= @duration %></b>. You can check the Payment Status or download the invoice <%= link_to 'here', transaction_path(@transaction) %>.
                <% else %>
                  <span class="badge">Pending</span>
                  Kindly pay your maintenance charges for <b><%= @duration %></b> on or before <b><%= @due_date %></b> to avoid late payment charges. If already paid, update the transaction details <%= link_to 'here', new_transaction_path %>.
                <% end %>
              </li>
              <li class="list-group-item">
                <% if @transaction_cf.present? %>
                  Thanks for your corpus fund payment for <b>Installment-<%= @duration_cf %></b>. You can check the Payment Status or download the invoice <%= link_to 'here', transaction_path(@transaction_cf) %>.
                <% else %>
                  <span class="badge">Pending</span>
                  Kindly pay your corpus fund for <b>Installment-<%= @duration_cf %></b> on or before <b><%= @due_date_cf %></b> to avoid late payment charges. If already paid, update the transaction details <%= link_to 'here', new_transaction_path %>.
                <% end %>
              </li>
              <li class="list-group-item">
                <span class="badge">NEW</span>
                You can upload your Profile picture <%= link_to 'here', (edit_member_path(current_member)+"#avatar") %>.
              </li>
              <li class="list-group-item">
                <span class="badge">NEW</span>
                You can do a Party Hall Booking <%= link_to 'here', booking_calendar_path %>.
              </li>
              <li class="list-group-item">
                <% if current_member.vehicles.length > 0 %>
                  Thanks for updating your Vehicle(s) information.
                <% else %>
                  <span class="badge">Pending</span>
                  Kindly add your Vehicle(s) details <%= link_to 'here', new_vehicle_path %>.
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 mtop10">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Bank Account Details</h3>
          </div>
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
              <li>
                <div class="modal fade" id="maintenanceAccountDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          <h2>APOWA Maintenance Account Details</h2>
                        </div>
                        <div class="panel-body panel30">
                          <dl class="dl-horizontal mtop20">
                            <dt>Account Name:</dt>
                            <dd>Ajantha Prime Owners Welfare Association</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Account Number:</dt>
                            <dd>04941010004961</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>IFSC Code:</dt>
                            <dd>SYNB0000494</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Bank:</dt>
                            <dd>SYNDICATE BANK</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Branch:</dt>
                            <dd>Electronic City</dd>
                          </dl>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="modal fade" id="corpusfundAccountDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          <h2>APOWA CorpusFund Account Details</h2>
                        </div>
                        <div class="panel-body panel30">
                          <dl class="dl-horizontal mtop20">
                            <dt>Account Name:</dt>
                            <dd>Corpus Fund Ajantha Prime Apartment</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Account Number:</dt>
                            <dd>04942010083655</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>IFSC Code:</dt>
                            <dd>SYNB0000494</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Bank:</dt>
                            <dd>SYNDICATE BANK</dd>
                          </dl>
                          <dl class="dl-horizontal mtop20">
                            <dt>Branch:</dt>
                            <dd>Electronic City</dd>
                          </dl>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <a href="javascript:void(0);" data-toggle="modal" data-target="#maintenanceAccountDetails">
                  <i class="fa fa-address-card fa-fw"></i>
                  APOWA Maintenace Account
                </a>
                <a href="javascript:void(0);" data-toggle="modal" data-target="#corpusfundAccountDetails">
                  <i class="fa fa-address-card fa-fw"></i>
                  APOWA CorpusFund Account
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 mtop10">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Documents</h3>
          </div>
          <div class="panel-body">
            <%# if current_member.admin? && current_member.admin_toggle? %>
              <!-- <div style="text-align: right;" class="mbottom10">
                <%#= form_tag :file_upload, multipart: true, class: "form-horizontal" do |f| %>
                  <%#= file_field_tag :my_file %>
                  <%#= submit_tag "Upload", class: "btn btn-primary" %>
                <%# end %>
              </div> -->
            <%# end %>
            <ul class="list-group">
              <% @documents.each do |file_name, file_path| %>
                <%# next if [".",".."].include?(file_name) %>
                <li class="list-group-item">
                  <%= file_name %>
                  <%#= link_to (root_url + "documents/#{URI.escape(file_name)}"), target: '_blank' do %>
                  <%= link_to (file_path + file_name), target: '_blank' do %>
                    <i class="fa fa-download fa-fw" title="Download"></i>
                  <% end %>
                  <%# if current_member.admin? %>
                    <%#= link_to file_remove_path(my_file: file_name), method: :delete, data: {confirm: "Are you sure?"} do %>
                      <!-- <i class="fa fa-trash-o fa-fw" title="Delete"></i> -->
                    <%# end %>
                  <%# end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/location.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            Location Map
          </h3>
        </div>

        <div class="panel-body panel30 flex-buttons">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.711473229385!2d77.66008334995293!3d12.861902890883385!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae6d807f12f6dd%3A0x7ed2c6e81cec379e!2sAjantha+Prime!5e0!3m2!1sen!2sin!4v1553065026397" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</div>