config/routes.rb
Rails.application.routes.draw do
  devise_for :member

  resources :home, only: [:index]
  resources :members
  resources :posts
  resources :comments
  resources :vehicles, except: [:show]
  resources :polls
  resources :votes, only: [:create]
  resources :facilities, path: :contacts
  resources :categories, except: [:show]
  resources :transactions do
    member do
      get 'download_receipt'
      put 'verify_payment'
    end
  end
  resources :bookings
  resources :feedbacks
  resources :settings, except: [:show]
  resources :accounts
  resources :inventories

  match '/members/:id/change_password', to: 'members#change_password', via: :get, as: :change_password
  match '/members/:id/update_password', to: 'members#update_password', via: :put, as: :update_password
  match '/members/:id/toggle_admin', to: 'members#toggle_admin', via: :put, as: :toggle_admin
  match '/members/:id/reset_password', to: 'members#reset_password', via: :put, as: :reset_password

  match '/posts/:id/publish', to: 'posts#publish', via: :put, as: :publish_post
  match '/all_transactions', to: 'transactions#all', via: :get, as: :all_transactions
  match '/all_bookings', to: 'bookings#all', via: :get, as: :all_bookings
  match '/booking_calendar', to: 'bookings#calendar', via: :get, as: :booking_calendar
  match '/file_upload', to: 'home#file_upload', via: :post, as: :file_upload
  match '/file_remove', to: 'home#file_remove', via: :delete, as: :file_remove
  get '/financial_reports', to: 'home#financial_reports'
  get '/location', to: 'home#location'
  get '/compose_mail', to: 'home#compose_mail'
  post '/notify_mail', to: 'home#notify_mail'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  belongs_to :member
  acts_as_commentable

  default_scope { where(visible: true) }
   
  validates :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :publish]
  before_action :check_admin, except: [:new, :create, :show, :index]

  # GET /posts
  def index
    @posts = current_member.admin? ? Post.unscoped : Post.where(private: false).or(Post.unscoped.where(member: current_member))
  end

  # GET /posts/1
  def show
    @new_comment = Comment.build_from(@post, current_member.id, "")
  end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.visible = false unless current_member.admin?
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def publish
    @post.update_attribute(:visible, !@post.visible)
    redirect_back(fallback_location: root_path, notice: "Post was successfully #{@post.visible? ? 'Published' : 'Unpublished'}")
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.unscoped.find(params[:id])
    end

    def check_admin
      unless current_member.admin? || current_member == @post.member
        flash[:error] = "You do not have access for this operation"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :private, :member_id, :visible, :active, :on_date)
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "form-horizontal") do |f| %>
  <%= resource_error_messages!(post) %>

  <%= f.hidden_field :member_id %>

  <div class="form-group">
    <%= f.label :title, "Title *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :on_date, "Posted Date *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 input-group">
      <%= f.text_field :on_date, class: "form-control datepicker", value: post.on_date.strftime("%d/%b/%Y"), autocomplete: :off %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :private, class: "control-label col-sm-2" do%>
      <span>
        Private
        <i class="fa fa-lightbulb-o fa-fw" title="Private posts will be visible only to its author and the governing members"></i>
      </span>
    <% end %>
    <div class="col-sm-10">
      <%= f.check_box :private, {class: "form-control", style: "width:34px"} %>
    </div>
  </div>

  <% if current_member.admin? %>
    <div class="form-group">
      <%= f.label :active, "Status", class: "control-label col-sm-2 fadmin" %>
      <div class="col-sm-10">
        <%= f.select(:active, [["Open",true],["Close",false]], {}, {class: "form-control"}) %>
      </div>
    </div>

    <!-- <div class="form-group">
      <%#= f.label :visible, class: "control-label col-sm-2" do%>
      <span>
        Publish
        <i class="fa fa-lightbulb-o fa-fw" title="Posts will be visible to everyone only if published"></i>
      </span>
    <%# end %>
      <div class="col-sm-10">
        <%#= f.check_box :visible, {class: "form-control", style: "width:34px"} %>
      </div>
    </div> -->
  <% end %>

  <div class="col-sm-12 flex-buttons">
    <%= link_to "Cancel", post, class: "btn btn-default" %>
    <%= f.submit "Submit", class: "mleft10 btn btn-primary" %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Editing Post</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <div class="flex-box">
            Posts
            <div class="col-lg-2">
              <% if current_member.admin? %>
                <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </h3>
      </div>
      <!-- /.panel-heading -->

      <div class="panel-body panel30 posts-wrapper">
        <table class="dataTable table table-striped table-bordered table-hover <%= current_member.admin? ? 'admin-view' : '' %>" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Title</th>
              <th>Author</th>
              <th>Posted Date</th>
              <th>Status</th>
              <th>
                Published?
                <i class="fa fa-lightbulb-o fa-fw" title="Posts will be published to everyone only if approved by governing members"></i>
              </th>
              <th>
                Private
                <i class="fa fa-lightbulb-o fa-fw" title="Private posts will be visible only to its author and the governing members"></i>
              </th>
              <% if current_member.admin? %>
                <th>Actions</th>
              <% end %>
            </tr>
          </thead>

          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= link_to post.title, post_path(post) %></td>
                <td><%= post.member.try(:name) %></td>
                <td><%= post.on_date.strftime("%d/%b/%Y") %></td>
                <td><%= post.active? ? 'Open' : 'Closed' %></td>
                <td><%= post.visible? ? 'Yes' : 'No' %></td>
                <td><%= post.private? ? 'Yes' : 'No' %></td>
                <% if current_member.admin? %>
                  <td>
                    <%= link_to post_path(post) do %>
                      <i class="fa fa-bell fa-fw" title="Open"></i>
                    <% end %>
                    <%= link_to edit_post_path(post) do %>
                      <i class="fa fa-pencil fa-fw" title="Edit"></i>
                    <% end %>
                    <% unless post.private? %>
                      <%= link_to publish_post_path(post), method: :put do %>
                        <i class="fa <%=post.visible? ? 'fa-stop' : 'fa-play'%> fa-fw" title="<%= post.visible? ? 'Unpublish' : 'Publish'%>"></i>
                      <% end %>
                    <% end %>
                    <%#= link_to post, method: :delete, data: {confirm: "Are you sure want to remove this post?"} do %>
                      <!-- <i class="fa fa-trash-o fa-fw" title="Delete"></i> -->
                    <%# end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>New Post</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            <div class="flex-box">
              <%= @post.title %>
              <% if current_member.admin? && !@post.private? %>
                <div class="col-lg-2">
                  <%= link_to publish_post_path(@post), method: :put, class: "btn btn-default mleft10" do %>
                    <i class="fa <%=@post.visible? ? 'fa-stop' : 'fa-play'%> fa-fw" title="<%= @post.visible? ? 'Unpublish' : 'Publish'%>"></i>
                    <%= @post.visible? ? 'Unpublish' : 'Publish'%>
                  <% end %>
                </div>
              <% end %>
              <% if @post.member == current_member || current_member.admin? %>
                <div class="col-lg-2">
                  <%= link_to edit_post_path(@post), class: "btn btn-default" do %>
                    <i class="fa fa-pencil-square-o fa-fw" title="Edit"></i>Edit
                  <% end %>
                </div>
              <% end %>
            </div>
          </h3>
          <b>Status:</b> <%= @post.active? ? 'Open' : 'Closed' %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <b>Published:</b> <%= @post.visible? ? 'Yes' : 'No' %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <b>Author:</b> <%= @post.member.name %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <b>Posted Date:</b> <%= @post.on_date.strftime("%d/%b/%Y") %>
        </div>
        <div class="panel-body panel30">
          <%= simple_format(@post.description) %>
        </div>
      </div>

      <%= render partial: "comments/template", locals: {commentable: @post, new_comment: @new_comment} %>

      <%= link_to '&#9664; Posts'.html_safe, posts_path, class: "btn btn-default" %>
    </div>
  </div>
</div>