config/routes.rb
Rails.application.routes.draw do
  devise_for :member

  resources :home, only: [:index]
  resources :members
  resources :posts
  resources :comments
  resources :vehicles, except: [:show]
  resources :polls
  resources :votes, only: [:create]
  resources :facilities, path: :contacts
  resources :categories, except: [:show]
  resources :transactions do
    member do
      get 'download_receipt'
      put 'verify_payment'
    end
  end
  resources :bookings
  resources :feedbacks
  resources :settings, except: [:show]
  resources :accounts
  resources :inventories

  match '/members/:id/change_password', to: 'members#change_password', via: :get, as: :change_password
  match '/members/:id/update_password', to: 'members#update_password', via: :put, as: :update_password
  match '/members/:id/toggle_admin', to: 'members#toggle_admin', via: :put, as: :toggle_admin
  match '/members/:id/reset_password', to: 'members#reset_password', via: :put, as: :reset_password

  match '/posts/:id/publish', to: 'posts#publish', via: :put, as: :publish_post
  match '/all_transactions', to: 'transactions#all', via: :get, as: :all_transactions
  match '/all_bookings', to: 'bookings#all', via: :get, as: :all_bookings
  match '/booking_calendar', to: 'bookings#calendar', via: :get, as: :booking_calendar
  match '/file_upload', to: 'home#file_upload', via: :post, as: :file_upload
  match '/file_remove', to: 'home#file_remove', via: :delete, as: :file_remove
  get '/financial_reports', to: 'home#financial_reports'
  get '/location', to: 'home#location'
  get '/compose_mail', to: 'home#compose_mail'
  post '/notify_mail', to: 'home#notify_mail'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_member!
  before_action :set_transaction, only: [:show, :edit, :update, :destroy, :download_receipt, :verify_payment]

  # GET /transactions
  def index
    @transactions = current_member.transactions
  end

  def all
    unless current_member.admin?
      flash[:error] = "You do not have access for this operation"
      redirect_to root_path
    else
      category_hash = params[:category].blank? ? {} : {category: params[:category]}
      @transactions = if params[:filter] == 'pending' || params[:filter].blank?
        Transaction.where.not(status: 'Verified')
      elsif params[:filter] == 'verified'
        Transaction.where(status: 'Verified')
      else
        Transaction
      end.where(category_hash)
      render action: 'index'
    end
  end

  # GET /transactions/1
  def show
  end

  # GET /transactions/new
  def new
    @transaction = current_member.transactions.build
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      redirect_to @transaction, notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /transactions/1
  def update
    if @transaction.update(transaction_params)
      if @transaction.Verified?
        MemberMailer.with(transaction: @transaction).verify_payment.deliver_later
      end
      redirect_to @transaction, notice: 'Transaction was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /transactions/1
  def destroy
    @transaction.destroy
    redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  def verify_payment
    if current_member.admin?
      @transaction.Verified!
      MemberMailer.with(transaction: @transaction).verify_payment.deliver_later
    end
    redirect_to all_transactions_path, notice: "Transaction was successfully verified."
  end

  def download_receipt
    respond_to do |format|
      format.html
      format.pdf {
        render pdf: "APOWA-Transaction-Receipt-#{@transaction.member.login}-#{Time.now.strftime('%v-%H:%M').to_s}",
        template: "transactions/download_receipt"
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
      check_admin
    end

    def check_admin
      unless current_member.admin? || current_member == @transaction.member
        flash[:error] = "You do not have access for this operation"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:payment_mode, :transaction_id, :amount_paid, :on_date, :category, :description, :member_id, :status, :penalty, :sub_category, :for_date)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_reason(transaction)
    if transaction.category == "Maintenance"
      "Maintenance Charge #{transaction.sub_category} (&#8377; #{transaction.per_month_maintenace} x 3 months)"
    elsif transaction.category == "CorpusFund"
      "Corpus Fund Installment-#{Transaction.sub_categories[transaction.sub_category]} (#{transaction.sub_category})"
    elsif transaction.category == "PartyHall"
      date = transaction.for_date.try(:strftime, "%d/%b/%Y").to_s
      "Party Hall Booking Charge #{date}"
    else
      transaction.category.titleize
    end.html_safe
  end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true, class: "form-horizontal") do |f| %>
  <%= resource_error_messages!(transaction) %>

  <% disabled = (transaction.Verified? || (!transaction.new_record? && current_member != transaction.member)) %>

  <%= f.hidden_field :member_id %>

  <div class="form-group">
    <%= f.label :payment_mode, "Payment Mode *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select(:payment_mode, Transaction.payment_modes.keys, {prompt: 'Select'}, {class: "form-control", disabled: disabled}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :transaction_id, (transaction.payment_mode=="Cheque" ? "Cheque Number *" : "Transaction # *"), class: "control-label col-sm-2 transaction_label" %>
    <div class="col-sm-10">
      <%= f.text_field :transaction_id, class: "form-control", disabled: disabled, readonly: (transaction.payment_mode=="Cash") %>
    </div>
  </div>

  <div class="form-group category">
    <%= f.label :category, "Category *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select(:category, Transaction.categories.keys, {prompt: 'Select'}, {class: "form-control", disabled: disabled}) %>
    </div>
  </div>

  <div class="form-group sub-category" style="<%=(transaction.Maintenance? || transaction.CorpusFund?) ? '' : 'display: none;'%>">
    <%= label_tag :sub_category, "Duration *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select(:sub_category, Transaction.sub_categories.keys, {prompt: 'Select'}, {class: "form-control", disabled: disabled}) %>
    </div>
  </div>

  <div class="form-group for-date" style="<%=transaction.PartyHall? ? '' : 'display: none;'%>">
    <%= label_tag :for_date, "Booking Date *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 input-group">
      <%= f.text_field :for_date, class: "form-control datepicker", value: transaction.for_date.try(:strftime, "%d/%b/%Y").to_s, autocomplete: :off, disabled: disabled %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :amount_paid, "Amount Paid (&#8377;) *".html_safe, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.number_field :amount_paid, class: "form-control", disabled: disabled %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :on_date, "Paid Date *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 input-group">
      <%= f.text_field :on_date, class: "form-control datepicker", value: (transaction.on_date || Date.today).strftime("%d/%b/%Y"), autocomplete: :off, disabled: disabled %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control", disabled: disabled %>
    </div>
  </div>

  <% if current_member.admin? %>
    <div class="form-group">
      <%= f.label :penalty, "Penalty", class: "control-label col-sm-2 fadmin" %>
      <div class="col-sm-10">
        <%= f.number_field :penalty, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :status, "Payment Status", class: "control-label col-sm-2 fadmin" %>
      <div class="col-sm-10">
        <%= f.select(:status, Transaction.statuses.keys, {prompt: 'Select'}, {class: "form-control"}) %>
      </div>
    </div>
  <% end %>

  <div class="col-sm-12 flex-buttons">
    <%= link_to 'Cancel', transaction, class: "btn btn-default" %>
    <%= f.submit "Submit", class: "mleft10 btn btn-primary" %>
  </div>
<% end %>

app/views/transactions/download_receipt.pdf.erb
<tr class="information mtop5">
  <td colspan="2">
    <table class="mtop20">
      <tr>
        <td>
          To:<br>
          <%= @transaction.member.name %><br>
          <%= @transaction.member.login %> Block
        </td>
        <td>
          Invoice #: <%= "%.4d" % @transaction.id %><br>
          Invoice Date: <%= @transaction.on_date.strftime("%d/%b/%Y") %><br>
          <% if @transaction.Maintenance? || @transaction.CorpusFund? %>
            Due Date: <%= @transaction.due_date %>
          <% end %>
        </td>
      </tr>
    </table>
  </td>
</tr>

<tr class="heading">
  <td>
    Payment Method
  </td>
  <td>
    Transaction #
  </td>
</tr>

<tr class="details">
  <td>
    <%= @transaction.payment_mode %>
  </td>
  <td>
    <%= @transaction.transaction_id %>
  </td>
</tr>

<tr class="heading">
  <td>
    Particulars
  </td>
  <td>
    Price
  </td>
</tr>

<tr class="item">
  <td>
    <%= transaction_reason(@transaction) %>
  </td>
  <td>
    &#8377; <%= "%.2f" % @transaction.actual_paid %>
  </td>
</tr>

<tr class="item last">
  <td>
    Penalty
  </td>
  <td>
    &#8377; <%= "%.2f" % @transaction.penalty %>
  </td>
</tr>

<tr class="total">
  <td></td>
  <td style="padding-top: 10px;">
    Total: &#8377; <%= "%.2f" % @transaction.amount_paid %>
  </td>
</tr>

app/views/transactions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Editing Transaction</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', transaction: @transaction %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading bbnone">
        <h3>
          <div class="flex-box">
            <div>
              <% if params[:action] == 'all' %>
                Transactions
                <%= select_tag "tr_category", options_for_select(Transaction.categories.keys, (params[:category])), prompt: 'All', class: "form-control", style: "width: 120px;display: inline;" %>
              <% else %>
                My Transaction(s)
              <% end %>
            </div>
            <div class="col-lg-2">
              <%= link_to 'Add My Transaction', new_transaction_path, class: "btn btn-default" %>
            </div>
          </div>
        </h3>
        <% if params[:action] == 'all' %>
          <ul class="nav nav-tabs">
            <li class="<%= (params[:filter]=='pending' || params[:filter].blank?) ? 'active' : '' %>">
              <%= link_to "Pending", all_transactions_path(category: params[:category], filter: 'pending') %>
            </li>
            <li class="<%= (params[:filter]=='verified') ? 'active' : '' %>">
              <%= link_to "Verified", all_transactions_path(category: params[:category], filter: 'verified') %>
            </li>
            <li class="<%= (params[:filter]=='all') ? 'active' : '' %>">
              <%= link_to "All", all_transactions_path(category: params[:category], filter: 'all') %>
            </li>
          </ul>
        <% end %>
      </div>
      <!-- /.panel-heading -->

      <div class="panel-body panel30 transactions-wrapper">
        <table class="dataTable table table-striped table-bordered table-hover <%= current_member.admin? ? 'admin-view' : '' %>" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Transaction #</th>
              <th>Payment Mode</th>
              <th>Amount Paid (&#8377;)</th>
              <th>Date Paid</th>
              <th>Category</th>
              <th>Duration</th>
              <th>Payment Status</th>
              <% if current_member.admin? %>
                <th>Paid By</th>
                <th>Phone</th>
              <% end %>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @transactions.each do |transaction| %>
              <tr>
                <td><%= link_to transaction.transaction_id, transaction %></td>
                <td><%= transaction.payment_mode %></td>
                <td><%= transaction.amount_paid %></td>
                <td><%= transaction.on_date.strftime("%d/%b/%Y") %></td>
                <td><%= transaction.category %></td>
                <td><%= transaction.sub_category %></td>
                <td><%= transaction.status %></td>
                <% if current_member.admin? %>
                  <td>
                    <%= link_to transaction.member.name_with_flat, member_path(transaction.member) %>
                  </td>
                  <td><%= transaction.member.phone %></td>
                <% end %>
                <td>
                  <% unless transaction.Verified? %>
                    <%= link_to edit_transaction_path(transaction) do %>
                      <i class="fa fa-pencil fa-fw" title="Edit"></i>
                    <% end %>
                    <% if current_member.admin? %>
                      <%= link_to verify_payment_transaction_path(transaction), method: :put do %>
                        <i class="fa fa-check fa-fw" title="Verify"></i>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= link_to download_receipt_transaction_path(transaction, format: :pdf) do %>
                      <i class="fa fa-download fa-fw" title="Download Receipt"></i>
                    <% end %>
                  <% end %>
                  <%#= link_to transaction, method: :delete, data: { confirm: 'Are you sure want to delate this transaction entry?' } do %>
                    <!-- <i class="fa fa-trash-o fa-fw" title="Delete"></i> -->
                  <%# end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Add Transaction</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', transaction: @transaction %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            <div class="flex-box">
              <%= @transaction.transaction_id %> - <%= @transaction.status %>
              <% if !@transaction.Verified? && (current_member.admin? || current_member == @transaction.member) %>
                <div class="col-lg-2">
                  <%= link_to edit_transaction_path(@transaction), class: "btn btn-default" do %>
                    <i class="fa fa-pencil-square-o fa-fw" title="Edit"></i>Edit
                  <% end %>
                </div>
              <% end %>
              <% if @transaction.Verified? %>
                <div class="col-lg-2">
                  <%= link_to download_receipt_transaction_path(@transaction, format: :pdf), class: "btn btn-default" do %>
                    <i class="fa fa-download fa-fw" title="Download Receipt"></i>Invoice
                  <% end %>
                </div>
              <% end %>
            </div>
          </h3>
        </div>
        <div class="panel-body panel30">
          <dl class="dl-horizontal mtop20">
            <dt>Transaction #:</dt>
            <dd><%= @transaction.transaction_id %></dd>
          </dl>
          <dl class="dl-horizontal mtop20">
            <dt>Payment Mode:</dt>
            <dd><%= @transaction.payment_mode %></dd>
          </dl>
          <dl class="dl-horizontal mtop20">
            <dt>Amount Paid:</dt>
            <dd>&#8377; <%= @transaction.amount_paid %></dd>
          </dl>
          <dl class="dl-horizontal mtop20">
            <dt>Penalty:</dt>
            <dd>&#8377; <%= @transaction.penalty %></dd>
          </dl>
          <dl class="dl-horizontal mtop20">
            <dt>Date Paid:</dt>
            <dd><%= @transaction.on_date.strftime("%d/%b/%Y") %></dd>
          </dl>
          <% if current_member.admin? %>
            <dl class="dl-horizontal mtop20">
              <dt>Paid By:</dt>
              <dd><%= link_to @transaction.member.name_with_flat, @transaction.member %></dd>
            </dl>
            <dl class="dl-horizontal mtop20">
              <dt>Phone:</dt>
              <dd><%= @transaction.member.phone %></dd>
            </dl>
          <% end %>
          <dl class="dl-horizontal mtop20">
            <dt>Category:</dt>
            <dd><%= @transaction.category %></dd>
          </dl>
          <% if @transaction.Maintenance? %>
            <dl class="dl-horizontal mtop20">
              <dt>Duration:</dt>
              <dd><%= @transaction.sub_category %></dd>
            </dl>
          <% elsif @transaction.CorpusFund? %>
            <dl class="dl-horizontal mtop20">
              <dt>Duration:</dt>
              <dd>Installment-<%= Transaction.sub_categories[@transaction.sub_category] %> (<%= @transaction.sub_category %>)</dd>
            </dl>
          <% elsif @transaction.PartyHall? %>
            <dl class="dl-horizontal mtop20">
              <dt>Booking Date:</dt>
              <dd><%= @transaction.for_date.try(:strftime, "%d/%b/%Y").to_s %></dd>
            </dl>
          <% end %>
          <dl class="dl-horizontal mtop20">
            <dt>Description:</dt>
            <dd><%= simple_format(@transaction.description) %></dd>
          </dl>
        </div>
      </div>

      <%= link_to '&#9664; My Transaction(s)'.html_safe, transactions_path, class: "btn btn-default" %>
      <%= link_to '&#9664; All Transactions'.html_safe, all_transactions_path, class: "mleft10 btn btn-default" if current_member.admin? %>
    </div>
  </div>
</div>