config/routes.rb
Rails.application.routes.draw do
  devise_for :member

  resources :home, only: [:index]
  resources :members
  resources :posts
  resources :comments
  resources :vehicles, except: [:show]
  resources :polls
  resources :votes, only: [:create]
  resources :facilities, path: :contacts
  resources :categories, except: [:show]
  resources :transactions do
    member do
      get 'download_receipt'
      put 'verify_payment'
    end
  end
  resources :bookings
  resources :feedbacks
  resources :settings, except: [:show]
  resources :accounts
  resources :inventories

  match '/members/:id/change_password', to: 'members#change_password', via: :get, as: :change_password
  match '/members/:id/update_password', to: 'members#update_password', via: :put, as: :update_password
  match '/members/:id/toggle_admin', to: 'members#toggle_admin', via: :put, as: :toggle_admin
  match '/members/:id/reset_password', to: 'members#reset_password', via: :put, as: :reset_password

  match '/posts/:id/publish', to: 'posts#publish', via: :put, as: :publish_post
  match '/all_transactions', to: 'transactions#all', via: :get, as: :all_transactions
  match '/all_bookings', to: 'bookings#all', via: :get, as: :all_bookings
  match '/booking_calendar', to: 'bookings#calendar', via: :get, as: :booking_calendar
  match '/file_upload', to: 'home#file_upload', via: :post, as: :file_upload
  match '/file_remove', to: 'home#file_remove', via: :delete, as: :file_remove
  get '/financial_reports', to: 'home#financial_reports'
  get '/location', to: 'home#location'
  get '/compose_mail', to: 'home#compose_mail'
  post '/notify_mail', to: 'home#notify_mail'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  include RailsSortable::Model
  set_sortable :sort, without_updating_timestamps: true
  
  belongs_to :member

  validates :title, :account_type, :payment_mode, :amount, :on_date, :for_month, presence: true
  validates :amount, numericality: {greater_than: 0}

  enum account_type: {Expense: 0, Income: 1}
  enum payment_mode: {Online: 0, Cheque: 1, Cash: 2}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_member!
  before_action :check_admin
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    duration = if params[:month].blank?
      Date.today.strftime("%b-%Y")
    else
      params[:month]
    end
    month, year = duration.split('-')
    @accounts = if params[:filter].present? && params[:filter] != 'all'
      Account.send(params[:filter].titleize)
    else
      Account
    end.where(for_month: duration).order(:sort)
    transactions = Transaction.where('extract(month from on_date) = ? AND extract(year from on_date) = ?', Date::ABBR_MONTHNAMES.index(month), year).Verified
    @maintenance_income = transactions.Maintenance.sum(&:amount_paid)
    @party_hall_income = transactions.PartyHall.sum(&:amount_paid)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def check_admin
      unless current_member.admin?
        flash[:error] = "You do not have access for this operation"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:title, :amount, :account_type, :payment_mode, :on_date, :for_month, :description, :member_id, :invoice_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def month_year_list
    list = []
    months = Date::ABBR_MONTHNAMES
    (2019..Date.today.year).to_a.each do |year|
      months[1..-1].each do |month|
        if year < Date.today.year || (year == Date.today.year && months.index(month) <= Date.today.month)
          list << (month + '-' + year.to_s)
        end
      end
    end
    list
  end
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true, class: "form-horizontal") do |f| %>
  <%= resource_error_messages!(account) %>

  <div class="form-group">
    <%= f.label :account_type, "Account Type *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select(:account_type, Account.account_types.keys, {prompt: 'Select'}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :member_id, "Payment By *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 autocomplete">
      <%= f.select(:member_id, flats_list_with_id, {prompt: 'Select'}, {class: "form-control", style: "display: none;"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, "Title *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :invoice_id, "Invoice/Bill #", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :invoice_id, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :amount, "Amount (&#8377;) *".html_safe, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :amount, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :payment_mode, "Payment Mode *", class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select(:payment_mode, Account.payment_modes.keys, {prompt: 'Select'}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :on_date, "Payment Date *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 input-group">
      <%= f.text_field :on_date, class: "form-control datepicker", value: (account.on_date || Date.today).strftime("%d/%b/%Y"), autocomplete: :off %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :for_month, "Month *", class: "control-label col-sm-2" %>
    <div class="col-sm-10 input-group">
      <%= f.text_field :for_month, class: "form-control monthpicker", value: (account.for_month || Date.today.strftime("%b-%Y")), autocomplete: :off %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="col-sm-12 flex-buttons">
    <%= link_to 'Cancel', account, class: "btn btn-default" %>
    <%= f.submit "Submit", class: "mleft10 btn btn-primary" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Editing Account Entry</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', account: @account %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading bbnone">
        <h3>
          <div class="flex-box">
            <div>
              Accounts
              <%= select_tag "for_month", options_for_select(month_year_list, (params[:month] || Date.today.strftime("%b-%Y"))), class: "form-control", style: "width: 130px;display: inline;" %>
            </div>
            <div class="col-lg-2">
              <%= link_to 'Add Account Entry', new_account_path, class: "btn btn-default" %>
            </div>
          </div>
        </h3>
        
        <ul class="nav nav-tabs">
          <li class="<%= (params[:filter]=='all' || params[:filter].blank?) ? 'active' : '' %>">
            <%= link_to "All", accounts_path(month: params[:month], filter: 'all') %>
          </li>
          <li class="<%= (params[:filter]=='expense') ? 'active' : '' %>">
            <%= link_to "Expense", accounts_path(month: params[:month], filter: 'expense') %>
          </li>
          <li class="<%= (params[:filter]=='income') ? 'active' : '' %>">
            <%= link_to "Income", accounts_path(month: params[:month], filter: 'income') %>
          </li>
        </ul>
      </div>
      <!-- /.panel-heading -->
      <div class='text-center'><small>Rows can be dragged & dropped to reorder.</small></div>

      <div class="panel-body panel30 accounts-wrapper">
        <table class="dataTable table table-striped table-bordered table-hover" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Title</th>
              <th>Payment Mode</th>
              <th>Date</th>
              <th>Payment By</th>
              <th>Amount (&#8377;)</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody class="sortable">
            <% total = 0 %>
            <% @accounts.each_with_sortable_id do |account, sortable_id| %>
              <tr id="<%= sortable_id %>">
                <td><%= link_to account.title, account %></td>
                <td><%= account.payment_mode %></td>
                <td><%= account.on_date.strftime("%d/%b/%Y") %></td>
                <td>
                  <%= link_to account.member.name_with_flat, member_path(account.member) %>
                </td>
                <td>
                  <%= account.Expense? ? '-' : '' %><%= account.amount %>
                  <% total = total.send((account.Expense? ? '-' : '+'), account.amount) %>
                </td>
                <td>
                  <%= link_to edit_account_path(account) do %>
                    <i class="fa fa-pencil fa-fw" title="Edit"></i>
                  <% end %>
                  <%= link_to account, method: :delete, data: { confirm: 'Are you sure want to delate this account entry?' } do %>
                    <i class="fa fa-trash-o fa-fw" title="Delete"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
          <% unless params[:filter]=='expense' %>
            <tbody>
              <tr>
                <td>Maintenance Charges</td>
                <td></td>
                <td></td>
                <td></td>
                <td><%= @maintenance_income %></td>
                <td></td>
              </tr>
              <tr>
                <td>PartyHall Charges</td>
                <td></td>
                <td></td>
                <td></td>
                <td><%= @party_hall_income %></td>
                <td></td>
              </tr>
            </tbody>
            <% total = total + @maintenance_income + @party_hall_income %>
          <% end %>
          <tfoot>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th style="text-align: right;">Total (&#8377;)</th>
              <th><%= total %></th>
              <th></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Add Account Entry</h3></div>
        <div class="panel-body panel30">
          <%= render 'form', account: @account %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            <div class="flex-box">
              <%= @account.title %>
              <div class="col-lg-2">
                <%= link_to edit_account_path(@account), class: "btn btn-default" do %>
                  <i class="fa fa-pencil-square-o fa-fw" title="Edit"></i>Edit
                <% end %>
              </div>
            </div>
          </h3>
        </div>
        <div class="panel-body panel30">
          <dl class="dl-horizontal mtop20">
            <dt>Account Type:</dt>
            <dd><%= @account.account_type %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Amount:</dt>
            <dd>&#8377; <%= @account.amount %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Payment Mode:</dt>
            <dd><%= @account.payment_mode %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Invoice/Bill #:</dt>
            <dd><%= @account.invoice_id %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Payment By:</dt>
            <dd><%= link_to @account.member.name_with_flat, @account.member %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Payment Date:</dt>
            <dd><%= @account.on_date %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Month:</dt>
            <dd><%= @account.for_month %></dd>
          </dl>

          <dl class="dl-horizontal mtop20">
            <dt>Description:</dt>
            <dd><%= simple_format(@account.description) %></dd>
          </dl>
        </div>
      </div>
      <%= link_to '&#9664; Accounts'.html_safe, accounts_path, class: "btn btn-default" %>
    </div>
  </div>
</div>